import { flatten, staircase as steps } from "../../tools/index";

export = {
    title: "back-deck-upper",
    units: "feet",
    righthand: "true",
    route: flatten([
        "goto back-deck portal side 1",
        "face street",
        "rotate 180",
        "move 9",
        "rotate 90",
        "move 37.83",
        "marker staircase side 1",
        "rotate -90",
        "move 8",
        "marker staircase side 2",
        "rotate -90",
        "move 37.83",
        "move 8",
        "rotate -90",
        "move 8",
        "move 9",
        "rotate -90",
        "move 8",
        "stop",
        "goto staircase side 1",
        "face street",
        "rotate -90",
        steps(),
        "descend 0.67",
        "move 6",
        "marker platform",
        "rotate -90",
        "move 8",
        "rotate -90",
        "move 6",
        steps(),
        "descend 0.67",
        "move 0.67",
        "marker ground level",
        "stop"
    ])
};