import { flatten, room, staircase } from "../../tools/index";

export = {
    title: "back-deck-upper",
    units: "feet",
    righthand: "true",
    route: flatten([
        "goto back-deck-portal",
        "face street",
        "rotate -90",
        "jump 4",
        "rotate -90",
        "move 9",
        "rotate 90",
        "move 37.83",
        "marker staircase side 1",
        "rotate -90",
        "move 8",
        "marker staircase side 2",
        "rotate -90",
        "move 37.83",
        "move 8",
        "rotate -90",
        "move 8",
        "move 9",
        "rotate -90",
        "move 8",
        "stop",
        "goto staircase side 1",
        "face street",
        "rotate -90",
        staircase(),
        "descend 0.67",
        "rotate -90",
        room({width: 8, depth: 6}),
        "jump 8",
        "rotate -90",
        staircase(),
        "descend 0.67",
        "rotate 90",
        "jump 4",
        "marker parking",
        "stop"
    ])
};