export = {
    title: "garage",
    units: "feet",
    righthand: "true",
    start: "telephone-pole",
    route: [
        "face street",
        "rotate -90",
        "jump 9",
        "rotate -90",
        "decend 3",
        "jump 36",
        "marker garage door side 1",
        "rotate 90",
        "move 20",
        "marker garage door side 2",
        "rotate -90",
        "move 18",
        "marker porch portal side 1",
        "jump 3",
        "marker porch portal side 2",
        "move 4",
        "marker connect to house",
        "rotate -90",
        "move 12",
        "rotate 90",
        "marker deck portal side 1",
        "move 19",
        "marker back-deck portal side 1",
        "rotate -90",
        "move 8",
        "marker back-deck portal side 2",
        "rotate -90",
        "move 19",
        "marker deck portal side 2",
        "move 25",
        "stop",
    ]
};